# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# Sensors
sensor:
  - platform: mitemp_bt
    mac: '*********'
    name: Melis Room Temp
    force_update: true
    median: 1
    monitored_conditions:
      - temperature
      - humidity
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
      
homekit:
  filter:
    exclude_entity_globs:
      - input_boolean.zigbee_permit_join
      - sensor.0x00158d0002b706d9_temperature


mqtt:
  broker: core-mosquitto # This will have to be your mqtt broker, Mosquitto addon is recommended.
  discovery: true


    
webhook:


